name: Deploy to Heroku

on:
  push:
    branches:
      - main  # 監聽 main 分支的變更

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 檢查程式碼
        uses: actions/checkout@v2

      - name: 安裝 Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: 登入 Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku auth:token

      - name: 設定 Heroku 遠端
        run: |
          heroku git:remote --app ${{ secrets.HEROKU_APP_NAME }}
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: 部署應用至 Heroku
        run: |
          git push heroku main --force
